apiVersion: v1
kind: Service

metadata:
  name: student-app
  namespace: student-system

spec:

  selector:
    app: student-app

  ports:

    - protocol: TCP
      port: 5000
      targetPort: 5000

  type: NodePort
